#!/usr/bin/env node
// Runs every registered QA scenario sequentially against the real Electron
// app + a stub backend, screenshots each one, and writes a walkbook
// (app/tests/qa/out/qa-report.md). Exit non-zero on any expect failure --
// this is a test suite that happens to produce a picture book, not a camera.
//
// Usage: node app/tests/qa/run.mjs [areaFilter]
//   areaFilter (optional): only run scenarios whose `area` matches exactly.

import path from 'node:path';
import { startStubBackend, launchApp, resetBackendState, snap, writeReportFile, OUT_DIR } from './harness.mjs';
import { scenarios } from './scenarios/index.mjs';

// One Electron launch for the whole run (like electron-smoke.spec.js's single
// beforeAll launch for its whole suite), not one per scenario: quitting
// Electron was found to terminate the parent runner process outright in this
// Electron/Playwright version combo (see harness.mjs's close() comment), so a
// per-scenario launch/quit loop would die after scenario 1. Between
// scenarios the SAME window gets a fresh backend state + reload instead.
async function runScenario(scenario, { page, stub }) {
  const backendState =
    typeof scenario.backendState === 'function' ? scenario.backendState() : scenario.backendState;
  const screenshots = [];
  let error = null;
  let negativeControlOutcome = null;

  try {
    await resetBackendState(page, stub, backendState);
    await scenario.navigate(page);

    if (scenario.kind === 'negative-control') {
      // The expectation is SUPPOSED to fail against a deliberately-lying
      // stub -- assert-the-assertion-fails. A negative control that passes
      // its own `expects` means the harness failed to catch the lie, which
      // is the actual failure mode here (not the inverse).
      try {
        await scenario.expects(page);
        negativeControlOutcome = 'FAILED: expectation unexpectedly passed against the lying stub';
        error = new Error('negative-control expectation unexpectedly passed (harness did not catch the lie)');
      } catch (_assertionError) {
        negativeControlOutcome = 'OK: correctly caught the lie';
      }
    } else {
      await scenario.expects(page);
    }

    for (const shot of scenario.screenshots || []) {
      const filePath = await snap(page, scenario.area, shot.name, shot.opts || {});
      screenshots.push(filePath);
    }
  } catch (e) {
    error = error || e;
  }

  return {
    area: scenario.area,
    name: scenario.name,
    kind: scenario.kind || 'standard',
    description: scenario.description,
    status: error ? 'FAIL' : 'PASS',
    error: error ? String((error && error.message) || error) : null,
    negativeControlOutcome,
    screenshots: screenshots.map((p) => path.relative(OUT_DIR, p)),
  };
}

function renderReport(results) {
  const byArea = new Map();
  for (const r of results) {
    if (!byArea.has(r.area)) byArea.set(r.area, []);
    byArea.get(r.area).push(r);
  }

  const totalPass = results.filter((r) => r.status === 'PASS').length;
  const lines = [];
  lines.push('# BetterFingers QA Walkbook');
  lines.push('');
  lines.push(
    `Generated by \`node app/tests/qa/run.mjs\`. ${totalPass}/${results.length} scenarios passed. ` +
      'Every screenshot below was taken against the REAL Electron app driven by a deterministic stub backend -- ' +
      'not a mockup. Determinism rules: fixed 1280x800 viewport, --force-device-scale-factor=1, TZ=UTC, ' +
      'animations disabled, dynamic regions masked (see harness.mjs DEFAULT_MASK_SELECTORS).',
  );
  lines.push('');

  for (const [area, areaResults] of byArea) {
    lines.push(`## ${area}`);
    lines.push('');
    for (const r of areaResults) {
      const badge = r.status === 'PASS' ? '✅ PASS' : '❌ FAIL';
      const kindTag = r.kind === 'negative-control' ? ' `negative-control`' : '';
      lines.push(`### ${r.name}${kindTag} — ${badge}`);
      lines.push('');
      lines.push(r.description);
      lines.push('');
      if (r.kind === 'negative-control' && r.negativeControlOutcome) {
        lines.push(`> Negative control result: ${r.negativeControlOutcome}`);
        lines.push('');
      }
      if (r.error) {
        lines.push('```');
        lines.push(r.error);
        lines.push('```');
        lines.push('');
      }
      for (const shot of r.screenshots) {
        lines.push(`![${r.name}](${shot})`);
        lines.push('');
      }
    }
  }
  return lines.join('\n');
}

async function main() {
  const areaFilter = process.argv[2];
  const selected = areaFilter ? scenarios.filter((s) => s.area === areaFilter) : scenarios;
  if (!selected.length) {
    console.error(`No scenarios matched area filter "${areaFilter}".`);
    return 1;
  }

  const firstState =
    typeof selected[0].backendState === 'function' ? selected[0].backendState() : selected[0].backendState;
  const stub = await startStubBackend(firstState);
  const harness = await launchApp({ backendPort: stub.port });

  const results = [];
  for (const scenario of selected) {
    process.stdout.write(`Running ${scenario.area}/${scenario.name}... `);
    const result = await runScenario(scenario, { page: harness.page, stub });
    results.push(result);
    console.log(result.status);
    if (result.error) {
      console.log(`  ${result.error}`);
    }
  }

  // Write the report and compute the exit code BEFORE closing Electron:
  // quitting was found to be able to take the whole runner process down with
  // it (see harness.mjs's close() comment), so anything that still needs to
  // run must happen first, not in a finally block after close().
  const reportPath = writeReportFile('qa-report.md', renderReport(results));
  const failed = results.filter((r) => r.status === 'FAIL');
  console.log(`\n${results.length - failed.length}/${results.length} passed. Report: ${reportPath}`);
  const exitCode = failed.length ? 1 : 0;

  await harness.close().catch(() => {});
  await stub.close().catch(() => {});
  return exitCode;
}

// Playwright's ElectronApplication.close() (used by harness.close()) does not
// reliably hand control back to a plain Node script in this Electron version
// (see the comment on close() in harness.mjs) -- explicit process.exit() is
// the deterministic way to end the runner instead of relying on the event
// loop draining naturally.
main()
  .then((code) => process.exit(code))
  .catch((e) => {
    console.error('QA runner crashed:', e);
    process.exit(1);
  });
