#!/usr/bin/env node
// Runs every registered QA scenario sequentially against the real Electron
// app + a stub backend, screenshots each one, and writes a walkbook
// (app/tests/qa/out/qa-report.md). Exit non-zero on any expect failure --
// this is a test suite that happens to produce a picture book, not a camera.
//
// Usage: node app/tests/qa/run.mjs [areaFilter]
//   areaFilter (optional): only run scenarios whose `area` matches exactly.

import path from 'node:path';
import {
  startStubBackend,
  launchApp,
  resetBackendState,
  snap,
  writeReportFile,
  OUT_DIR,
  TARGET,
  DEFAULT_SCENARIO_UI,
} from './harness.mjs';
import { scenarios } from './scenarios/index.mjs';
import { ALPHA_CAPABILITIES } from '../../src/renderer/config/alphaCapabilities.js';

// One Electron launch for the whole run (like electron-smoke.spec.js's single
// beforeAll launch for its whole suite), not one per scenario: quitting
// Electron was found to terminate the parent runner process outright in this
// Electron/Playwright version combo (see harness.mjs's close() comment), so a
// per-scenario launch/quit loop would die after scenario 1. Between
// scenarios the SAME window gets a fresh backend state + reload instead.
// `ctx` is the second argument every navigate()/expects()/screenshot hook gets.
// It exists for the two floating production windows (overlay.html,
// review-overlay.html): they are separate BrowserWindows, so a scenario that
// only ever received the dashboard `page` could not reach them at all, which is
// why they had zero QA before Wave 11B. `ctx.app` is the ElectronApplication,
// which already tracks every window the app owns -- see harness.mjs's
// auxiliaryWindow(). Scenarios that do not need it ignore the argument, so this
// is additive to all pre-existing ones.
async function runScenario(scenario, { page, stub, app }) {
  const backendState =
    typeof scenario.backendState === 'function' ? scenario.backendState() : scenario.backendState;
  const screenshots = [];
  const ctx = { app, stub };
  let error = null;
  let negativeControlOutcome = null;

  try {
    await resetBackendState(page, stub, backendState);
    await scenario.navigate(page, ctx);

    if (scenario.kind === 'negative-control') {
      // The expectation is SUPPOSED to fail against a deliberately-lying
      // stub -- assert-the-assertion-fails. A negative control that passes
      // its own `expects` means the harness failed to catch the lie, which
      // is the actual failure mode here (not the inverse).
      try {
        await scenario.expects(page, ctx);
        negativeControlOutcome = 'FAILED: expectation unexpectedly passed against the lying stub';
        error = new Error('negative-control expectation unexpectedly passed (harness did not catch the lie)');
      } catch (_assertionError) {
        negativeControlOutcome = 'OK: correctly caught the lie';
      }
    } else {
      await scenario.expects(page, ctx);
    }

    for (const shot of scenario.screenshots || []) {
      // `shot.of` lets a scenario photograph a window other than the dashboard
      // (the overlays). Default stays `page`, so every existing entry is
      // unchanged. Resolved per shot rather than per scenario because a
      // scenario may legitimately want both windows in its walkbook entry.
      const target = shot.of ? await shot.of(ctx) : page;
      const filePath = await snap(target, scenario.area, shot.name, shot.opts || {});
      screenshots.push(filePath);
    }
  } catch (e) {
    error = error || e;
  }

  return {
    area: scenario.area,
    name: scenario.name,
    kind: scenario.kind || 'standard',
    description: scenario.description,
    status: error ? 'FAIL' : 'PASS',
    error: error ? String((error && error.message) || error) : null,
    negativeControlOutcome,
    screenshots: screenshots.map((p) => path.relative(OUT_DIR, p)),
  };
}

function renderReport(results, skipped = []) {
  const byArea = new Map();
  for (const r of results) {
    if (!byArea.has(r.area)) byArea.set(r.area, []);
    byArea.get(r.area).push(r);
  }

  const totalPass = results.filter((r) => r.status === 'PASS').length;
  const lines = [];
  lines.push('# BetterFingers QA Walkbook');
  lines.push('');

  if (skipped.length) {
    const byCapability = new Map();
    for (const scenario of skipped) {
      const capability = scenario.requiredCapability;
      if (!byCapability.has(capability)) byCapability.set(capability, []);
      byCapability.get(capability).push(`${scenario.area}/${scenario.name}`);
    }
    lines.push(`Skipped ${skipped.length} scenarios for capabilities disabled in the alpha release surface:`);
    lines.push('');
    for (const [capability, names] of byCapability) {
      lines.push(`- \`${capability}\`: ${names.join(', ')}`);
    }
    lines.push('');
  }
  lines.push(
    `Generated by \`node app/tests/qa/run.mjs\`. ${totalPass}/${results.length} scenarios passed. ` +
      'Every screenshot below was taken against the REAL Electron app driven by a deterministic stub backend -- ' +
      'not a mockup. Determinism rules: fixed 1280x800 viewport, --force-device-scale-factor=1, TZ=UTC, ' +
      'animations disabled, dynamic regions masked (see harness.mjs DEFAULT_MASK_SELECTORS).',
  );
  lines.push('');

  for (const [area, areaResults] of byArea) {
    lines.push(`## ${area}`);
    lines.push('');
    for (const r of areaResults) {
      const badge = r.status === 'PASS' ? '✅ PASS' : '❌ FAIL';
      const kindTag = r.kind === 'negative-control' ? ' `negative-control`' : '';
      lines.push(`### ${r.name}${kindTag} — ${badge}`);
      lines.push('');
      lines.push(r.description);
      lines.push('');
      if (r.kind === 'negative-control' && r.negativeControlOutcome) {
        lines.push(`> Negative control result: ${r.negativeControlOutcome}`);
        lines.push('');
      }
      if (r.error) {
        lines.push('```');
        lines.push(r.error);
        lines.push('```');
        lines.push('');
      }
      for (const shot of r.screenshots) {
        lines.push(`![${r.name}](${shot})`);
        lines.push('');
      }
    }
  }
  return lines.join('\n');
}

async function main() {
  const areaFilter = process.argv[2];
  // A scenario is written against one UI's element ids and is meaningless
  // against the other (the dashboards share no ids at all), so scenarios
  // declare their target via `ui`. Without this filter, running either target
  // drags in the other's scenarios and reports a wall of "element not found"
  // that looks like a broken app.
  //
  // Untagged scenarios default to `legacy`, NOT to whatever the default RUN
  // target is. Those scenarios were all written against index.html's ids, and
  // the Wave 11 flip changed which page a bare `node run.mjs` opens -- not
  // which page they were written for. Tying the two together would have
  // silently pointed ~37 legacy scenarios at the production page.
  const forTarget = scenarios.filter((s) => (s.ui || DEFAULT_SCENARIO_UI) === TARGET.name);
  const requested = areaFilter ? forTarget.filter((s) => s.area === areaFilter) : forTarget;
  const skipped = requested.filter(
    (scenario) => scenario.requiredCapability
      && ALPHA_CAPABILITIES[scenario.requiredCapability] !== true,
  );
  const selected = requested.filter((scenario) => !skipped.includes(scenario));
  if (!selected.length) {
    const detail = areaFilter ? `area filter "${areaFilter}" on ` : '';
    console.error(`No scenarios matched ${detail}UI target "${TARGET.name}".`);
    return 1;
  }

  const firstState =
    typeof selected[0].backendState === 'function' ? selected[0].backendState() : selected[0].backendState;
  const stub = await startStubBackend(firstState);
  // Say which app is under test: the two UIs share no element ids, so a run
  // against the wrong target fails in confusing ways ("element not found" for
  // everything) unless the target is stated up front.
  console.log(`UI target: ${TARGET.name} (${TARGET.page})`);
  const harness = await launchApp({ backendPort: stub.port });

  if (skipped.length) {
    const summary = skipped
      .map((scenario) => `${scenario.area}/${scenario.name} (${scenario.requiredCapability})`)
      .join(', ');
    console.log(`Skipping ${skipped.length} disabled-capability scenarios: ${summary}`);
  }

  const results = [];
  for (const scenario of selected) {
    process.stdout.write(`Running ${scenario.area}/${scenario.name}... `);
    const result = await runScenario(scenario, { page: harness.page, stub, app: harness.app });
    results.push(result);
    console.log(result.status);
    if (result.error) {
      console.log(`  ${result.error}`);
    }
  }

  // Write the report and compute the exit code BEFORE closing Electron:
  // quitting was found to be able to take the whole runner process down with
  // it (see harness.mjs's close() comment), so anything that still needs to
  // run must happen first, not in a finally block after close().
  // A FILTERED run must never overwrite the full-board walkbook.
  //
  // `qa-report.md` is read as the evidence of record for the whole board. An
  // area run produces a report covering only that area, and writing it to the
  // same filename silently replaced 97 scenarios' evidence with 6 -- the file
  // still looked like the walkbook, still had a plausible pass line, and the
  // only clue was that it had got much shorter. That happened during this wave:
  // a single `run.mjs overlay-windows` truncated the committed aggregate by 589
  // lines, and it was caught by reading `git status`, not by anything here.
  //
  // Filtered runs now write `qa-report.<area>.md` instead. The aggregate can
  // only ever be produced by a run that actually covered the whole board, which
  // is the only run entitled to claim it.
  const reportName = areaFilter ? `qa-report.${areaFilter}.md` : 'qa-report.md';
  const reportPath = writeReportFile(reportName, renderReport(results, skipped));
  const failed = results.filter((r) => r.status === 'FAIL');
  console.log(`\n${results.length - failed.length}/${results.length} passed. Report: ${reportPath}`);
  if (areaFilter) {
    console.log(
      `(filtered run: wrote ${reportName}, leaving the full-board qa-report.md untouched)`,
    );
  }
  const exitCode = failed.length ? 1 : 0;
  // Stage the code on the process BEFORE closing Electron, not just in a
  // local: closing can terminate this process outright (harness.mjs close()),
  // in which case the `process.exit(code)` below never runs and the shell saw
  // a green 0 for a red run -- i.e. the suite could not fail a build at all.
  // `process.exitCode` is honoured by whatever exit path actually wins.
  process.exitCode = exitCode;

  await harness.close().catch(() => {});
  await stub.close().catch(() => {});
  return exitCode;
}

// Playwright's ElectronApplication.close() (used by harness.close()) does not
// reliably hand control back to a plain Node script in this Electron version
// (see the comment on close() in harness.mjs) -- explicit process.exit() is
// the deterministic way to end the runner instead of relying on the event
// loop draining naturally.
main()
  .then((code) => process.exit(code))
  .catch((e) => {
    console.error('QA runner crashed:', e);
    process.exit(1);
  });
